In [17]:
%pip install duckdb

Requirement already satisfied: duckdb in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (1.5.3)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [18]:
import duckdb

con = duckdb.connect("../data/shelterflow.duckdb")
intakes = con.execute("SELECT * FROM bronze_intakes").df()
outcomes = con.execute("SELECT * FROM bronze_outcomes").df()

# Exploratory Data Analysis of Shelter Intakes & Outcomes

## Intakes
### Column Info

In [19]:
intakes.info()

<class 'pandas.DataFrame'>
RangeIndex: 80187 entries, 0 to 80186
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age_upon_intake   80187 non-null  str
 1   animal_id         80187 non-null  str
 2   animal_type       80187 non-null  str
 3   breed             80187 non-null  str
 4   color             80187 non-null  str
 5   datetime          80187 non-null  str
 6   datetime2         80187 non-null  str
 7   found_location    80187 non-null  str
 8   intake_condition  80187 non-null  str
 9   intake_type       80187 non-null  str
 10  name              55603 non-null  str
 11  sex_upon_intake   80186 non-null  str
dtypes: str(12)
memory usage: 7.3 MB

### Descriptive Statistics

In [20]:
intakes.describe()

,age_upon_intake,animal_id,animal_type,breed,color,datetime,datetime2,found_location,intake_condition,intake_type,name,sex_upon_intake
count,80187,80187,80187,80187,80187,80187,80187,80187,80187,80187,55603,80186
unique,46,72365,5,2166,529,57055,57055,36772,8,5,14731,5
top,1 year,A721033,Dog,Domestic Shorthair Mix,Black/White,2016-09-23T12:00:00.000,2016-09-23T12:00:00.000,Austin (TX),Normal,Stray,Bella,Intact Male
freq,14672,13,45743,23519,8340,64,64,14443,70520,56280,357,25488

### Missing Values

In [21]:
intakes.isnull().sum()

age_upon_intake         0
animal_id               0
animal_type             0
breed                   0
color                   0
datetime                0
datetime2               0
found_location          0
intake_condition        0
intake_type             0
name                24584
sex_upon_intake         1
dtype: int64

### Duplicate Rows

In [22]:
intakes.duplicated().sum()

26

### Breed Distribution

In [23]:
intakes["breed"].value_counts()

breed
Domestic Shorthair Mix              23519
Pit Bull Mix                         6382
Chihuahua Shorthair Mix              4860
Labrador Retriever Mix               4841
Domestic Medium Hair Mix             2337
                                    ...
Siamese/Snowshoe                        1
Yorkshire Terrier/Dachshund             1
Guinea                                  1
Norfolk Terrier/Pug                     1
Australian Shepherd/Basset Hound        1
Name: count, Length: 2166, dtype: int64

### Intake Type Distribution

In [24]:
intakes["intake_type"].value_counts()

intake_type
Stray                 56280
Owner Surrender       15156
Public Assist          5033
Wildlife               3467
Euthanasia Request      251
Name: count, dtype: int64

### Animal Type Distribution

In [25]:
intakes["animal_type"].value_counts()

animal_type
Dog          45743
Cat          29659
Other         4434
Bird           342
Livestock        9
Name: count, dtype: int64


## Outcomes
### Column Info

In [26]:
outcomes.info()

<class 'pandas.DataFrame'>
RangeIndex: 80681 entries, 0 to 80680
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age_upon_outcome  80673 non-null  str
 1   animal_id         80681 non-null  str
 2   animal_type       80681 non-null  str
 3   breed             80681 non-null  str
 4   color             80681 non-null  str
 5   date_of_birth     80681 non-null  str
 6   datetime          80681 non-null  str
 7   monthyear         80681 non-null  str
 8   name              56116 non-null  str
 9   outcome_subtype   36893 non-null  str
 10  outcome_type      80667 non-null  str
 11  sex_upon_outcome  80679 non-null  str
dtypes: str(12)
memory usage: 7.4 MB

### Descriptive Statistics

In [27]:
outcomes.describe()

,age_upon_outcome,animal_id,animal_type,breed,color,date_of_birth,datetime,monthyear,name,outcome_subtype,outcome_type,sex_upon_outcome
count,80673,80681,80681,80681,80681,80681,80681,80681,56116,36893,80667,80679
unique,46,72877,5,2176,532,5956,66474,66474,14824,19,9,5
top,1 year,A721033,Dog,Domestic Shorthair Mix,Black/White,2014-05-05T00:00:00,2016-04-18T00:00:00,2016-04-18T00:00:00,Bella,Partner,Adoption,Neutered Male
freq,14911,13,45856,23821,8396,112,39,39,362,20082,34232,28702

### Missing Values

In [28]:
outcomes.isnull().sum()

age_upon_outcome        8
animal_id               0
animal_type             0
breed                   0
color                   0
date_of_birth           0
datetime                0
monthyear               0
name                24565
outcome_subtype     43788
outcome_type           14
sex_upon_outcome        2
dtype: int64

### Duplicate Rows

In [29]:
outcomes.duplicated().sum()

10

### Breed Distribution

In [30]:
outcomes["breed"].value_counts()

breed
Domestic Shorthair Mix          23821
Pit Bull Mix                     6361
Chihuahua Shorthair Mix          4874
Labrador Retriever Mix           4849
Domestic Medium Hair Mix         2368
                                ...
Guinea                              1
Norfolk Terrier/Pug                 1
Pomeranian/Beagle                   1
Chickadee Mix                       1
Labrador Retriever/Pekingese        1
Name: count, Length: 2176, dtype: int64

### Outcome Type Distribution

In [31]:
outcomes["outcome_type"].value_counts()

outcome_type
Adoption           34232
Transfer           24050
Return to Owner    14851
Euthanasia          6289
Died                 699
Disposal             304
Rto-Adopt            179
Missing               47
Relocate              16
Name: count, dtype: int64

### Animal Type Distribution

In [32]:
outcomes["animal_type"].value_counts()

animal_type
Dog          45856
Cat          30028
Other         4446
Bird           341
Livestock       10
Name: count, dtype: int64


## Key Findings
* The most common dog breed at the shelter is a Pit Bull Mix.
* The most common cat breed at the shelter is a Domestic Shorthair Mix.
    * It is worth noting that this is a very generalized breed which does not take into account cat color (which prospective adopters may factor into their decision to adopt). Thus, animal breed and color may need to be considered together for accurate analysis.
* The majority of animals at the shelter are dogs, followed by cats.
* `datetime`, `datetime2`, `date_of_birth`, and `monthyear` are stored as `str` type instead of `datetime` type.
* There is a large amount of null `name` values that need to be handled.
* `age_upon_intake` and `age_upon_outcome` are currently stored as `str` type and require parsing.